#!/usr/bin/env bash
# -*- ENCODING: UTF-8 -*-
##
## @author     Raúl Caro Pastorino
## @copyright  Copyright © 2018 Raúl Caro Pastorino
## @license    https://wwww.gnu.org/licenses/gpl.txt
## @email      dev@fryntiz.es
## @web        https://fryntiz.es
## @gitlab     https://gitlab.com/fryntiz
## @github     https://github.com/fryntiz
## @twitter    https://twitter.com/fryntiz
##
##             Guía de estilos aplicada:
## @style      https://gitlab.com/fryntiz/bash-guide-style

############################
##     INSTRUCCIONES      ##
############################
## Archivo de configuración con las constantes utilizadas durante el
## proceso de instalación y configuración de GNU/Linux Gentoo

############################
##         GLOBAL         ##
############################
WORKSCRIPT=$PWD        ## Directorio principal del script
USER=$(whoami)         ## Usuario que ejecuta el script
VERSION='0.0.1'        ## Primera versión del script
LOGERROR='/tmp/installerErrors.log'  ## Archivo donde almacenar errores

############################
##        USUARIO         ##
############################
USUARIO='usuario'      ## Nombre del usuario a crear

############################
##          RED           ##
############################
HOSTNAME='localhost'   ## Nombre del EQUIPO
DOMAIN='local'         ## Nombre del dominio

############################
##      PARTICIONES       ##
############################
BOOT='/dev/sdXX'       ## Partición BOOT de 1GB
RAIZ='/dev/sdXX'       ## Partición Raíz de más de 10GB
SWAP='/dev/sdXX'       ## Partición SWAP
JAULA='/mnt/gentoo'    ## Lugar donde montar el entorno chroot
HDROOT='hdX,X'         ## Partición raíz / en nomenclatura hd0,1
LUKSNAME='LUKSGENTOO'  ## Nombre de la partición RAIZ cifrada

############################
##        STAGE 3         ##
############################
SYSTEMD=true           ## Indica si se instalará con systemd el stage3

STAGE3='stage3-amd64-20180828T214505Z.tar.xz'
RUTASTAGE3="http://distfiles.gentoo.org/releases/amd64/autobuilds/current-stage3-amd64/$STAGE3"

STAGE3SYSTEMD='stage3-amd64-systemd-20180827.tar.bz2'
RUTASTAGE3SYSTEMD="http://distfiles.gentoo.org/releases/amd64/autobuilds/current-stage3-amd64-systemd/$STAGE3SYSTEMD"

############################
##         LOCALE         ##
############################
KEYMAP="es"
LOCALIZATION='es_ES.UTF-8'
ZONE='Europe/Madrid'
